"""Canonical evidence API: observe, normalize, canonicalize, and persist facts."""

from .artifacts import (
    current_run_artifact,
    identity_stable,
    is_direct_child,
    load_json_object,
    paths_distinct,
    snapshot_unchanged,
    summarize_checks,
    write_json_bundle,
)
from .errors import (
    ERROR_LEDGER_SCHEMA_VERSION,
    Attribution,
    AttributionConfidence,
    AttributionSignals,
    ErrorCategory,
    ErrorEvent,
    ErrorLedger,
    append_error_event,
    build_error_event,
    classify_attribution,
    default_ledger_path,
    error_fingerprint,
    read_error_events,
    summarize_error_events,
)
from .identity import (
    create_collision_safe_directory,
    ensure_fresh_directory,
    identity_record,
    sha256_file,
    utc_timestamp,
)
from .normalization import (
    extract_jacobian_evidence,
    first_failed_reason,
)
from .schema import (
    CELL_KEY_COLUMNS,
    CORE_FACE_CONTRACT,
    DEFAULT_FACE_CONTRACT,
    FACE_REQUIRED_COLUMNS,
    GREEN_GAUSS_FACE_CONTRACT,
    ColumnRole,
    ColumnSpec,
    CoreColumnRole,
    DynamicSchemaContract,
    SchemaResolution,
    normalize_and_project,
    require_columns,
)
from .store import EvidenceStore
from .synthetic import rz_constant_square_face_rows
from .transform import normalize_face_evidence

__all__ = [
    "Attribution",
    "AttributionConfidence",
    "AttributionSignals",
    "CELL_KEY_COLUMNS",
    "CORE_FACE_CONTRACT",
    "DEFAULT_FACE_CONTRACT",
    "ERROR_LEDGER_SCHEMA_VERSION",
    "ErrorCategory",
    "ErrorEvent",
    "ErrorLedger",
    "EvidenceStore",
    "FACE_REQUIRED_COLUMNS",
    "GREEN_GAUSS_FACE_CONTRACT",
    "ColumnRole",
    "ColumnSpec",
    "CoreColumnRole",
    "DynamicSchemaContract",
    "SchemaResolution",
    "append_error_event",
    "build_error_event",
    "classify_attribution",
    "create_collision_safe_directory",
    "current_run_artifact",
    "default_ledger_path",
    "ensure_fresh_directory",
    "error_fingerprint",
    "extract_jacobian_evidence",
    "first_failed_reason",
    "identity_record",
    "identity_stable",
    "is_direct_child",
    "load_json_object",
    "normalize_and_project",
    "normalize_face_evidence",
    "paths_distinct",
    "read_error_events",
    "require_columns",
    "rz_constant_square_face_rows",
    "sha256_file",
    "snapshot_unchanged",
    "summarize_checks",
    "summarize_error_events",
    "utc_timestamp",
    "write_json_bundle",
]
