"""Legacy compatibility facade for :mod:`qpx_harness.evidence_engine`.

All evidence implementation now lives in ``evidence_engine``. This package
exports only its historical public surface so existing campaign code can migrate
without carrying a second implementation.
"""
from qpx_harness.evidence_engine import (
    Attribution,
    AttributionConfidence,
    AttributionSignals,
    ErrorCategory,
    ErrorEvent,
    ErrorLedger,
    append_error_event,
    build_error_event,
    classify_attribution,
    create_collision_safe_directory,
    current_run_artifact,
    default_ledger_path,
    ensure_fresh_directory,
    error_fingerprint,
    identity_record,
    identity_stable,
    is_direct_child,
    load_json_object,
    paths_distinct,
    read_error_events,
    sha256_file,
    snapshot_unchanged,
    summarize_checks,
    summarize_error_events,
    utc_timestamp,
    write_json_bundle,
)

__all__ = [
    "Attribution",
    "AttributionConfidence",
    "AttributionSignals",
    "ErrorCategory",
    "ErrorEvent",
    "ErrorLedger",
    "append_error_event",
    "build_error_event",
    "classify_attribution",
    "create_collision_safe_directory",
    "current_run_artifact",
    "default_ledger_path",
    "ensure_fresh_directory",
    "error_fingerprint",
    "identity_record",
    "identity_stable",
    "is_direct_child",
    "load_json_object",
    "paths_distinct",
    "read_error_events",
    "sha256_file",
    "snapshot_unchanged",
    "summarize_checks",
    "summarize_error_events",
    "utc_timestamp",
    "write_json_bundle",
]
