"""Unified numerical evidence collection, persistence, and diagnosis engine."""

from .diagnosis import (
    DiagnosticMetricSpec,
    DiagnosisReport,
    DiagnosisRule,
    DiagnosisRuleRegistry,
    EvidenceTolerances,
    FailureLocation,
    MetricPredicate,
    Z3Decision,
    Z3DiagnosisEngine,
    Z3OwnerRule,
    Z3RuleSet,
    build_constant_state_registry,
    build_constant_state_ruleset,
    evaluate_diagnosis_registry,
    ruleset_from_registry,
    summarize_constant_state,
    summarize_constant_state_report,
)
from .errors import (
    ERROR_LEDGER_SCHEMA_VERSION,
    ErrorLedger,
    error_record,
    merge_error_records,
)
from .provenance import (
    artifact_created_utc,
    canonical_identity_annotations,
    canonical_identity_fields,
    infer_attempt_id,
    load_attempt_identity,
    normalize_git_commit,
    normalize_image_reference,
    write_attempt_identity,
)
from .schema import (
    CELL_KEY_COLUMNS,
    CORE_FACE_CONTRACT,
    DEFAULT_FACE_CONTRACT,
    FACE_REQUIRED_COLUMNS,
    GREEN_GAUSS_FACE_CONTRACT,
    ColumnRole,
    ColumnSpec,
    CoreColumnRole,
    DynamicSchemaContract,
    SchemaResolution,
    normalize_and_project,
    require_columns,
)
from .store import EvidenceStore
from .transform import build_cell_evidence, prepare_face_evidence, write_evidence_bundle

__all__ = [
    "CELL_KEY_COLUMNS",
    "CORE_FACE_CONTRACT",
    "DEFAULT_FACE_CONTRACT",
    "ERROR_LEDGER_SCHEMA_VERSION",
    "FACE_REQUIRED_COLUMNS",
    "GREEN_GAUSS_FACE_CONTRACT",
    "ColumnRole",
    "ColumnSpec",
    "CoreColumnRole",
    "DiagnosticMetricSpec",
    "DiagnosisReport",
    "DiagnosisRule",
    "DiagnosisRuleRegistry",
    "DynamicSchemaContract",
    "ErrorLedger",
    "EvidenceStore",
    "EvidenceTolerances",
    "FailureLocation",
    "MetricPredicate",
    "SchemaResolution",
    "Z3Decision",
    "Z3DiagnosisEngine",
    "Z3OwnerRule",
    "Z3RuleSet",
    "artifact_created_utc",
    "build_cell_evidence",
    "build_constant_state_registry",
    "build_constant_state_ruleset",
    "canonical_identity_annotations",
    "canonical_identity_fields",
    "error_record",
    "evaluate_diagnosis_registry",
    "infer_attempt_id",
    "load_attempt_identity",
    "merge_error_records",
    "normalize_and_project",
    "normalize_git_commit",
    "normalize_image_reference",
    "prepare_face_evidence",
    "require_columns",
    "ruleset_from_registry",
    "summarize_constant_state",
    "summarize_constant_state_report",
    "write_attempt_identity",
    "write_evidence_bundle",
]
