#!/usr/bin/env python3

"""Issue #32 one-step real-QPX performance profiler.

This profiler is intentionally non-invasive: it does not edit the target input,
change dt/tolerances/physics, or copy case assets.  It adds diagnostic objects by
merging a generated MOOSE overlay, limits the transient to one physical timestep,
and records MOOSE PerfGraph plus PETSc logging while streaming QPX output live.

Example:
  python3 scripts/r32_profile_qpx_case.py \
    --case-dir /path/to/case --input input.i --label T2-heavy

QPX executable resolution order:
  --qpx, QPX_EXECUTABLE, <case-dir>/qpx-opt, PATH.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def resolve_executable(case_dir: Path, explicit: str | None) -> Path:
    candidates: list[Path] = []
    if explicit:
        candidates.append(Path(explicit).expanduser())
    if os.environ.get("QPX_EXECUTABLE"):
        candidates.append(Path(os.environ["QPX_EXECUTABLE"]).expanduser())
    candidates.append(case_dir / "qpx-opt")

    found = shutil.which("qpx-opt")
    if found:
        candidates.append(Path(found))

    for candidate in candidates:
        try:
            resolved = candidate.resolve()
        except FileNotFoundError:
            continue
        if resolved.is_file() and os.access(resolved, os.X_OK):
            return resolved

    raise SystemExit(
        "qpx-opt not found. Supply --qpx, set QPX_EXECUTABLE, place qpx-opt in "
        "the case directory, or add qpx-opt to PATH."
    )


def ensure_fresh_output_dir(path: Path) -> None:
    if path.exists() and any(path.iterdir()):
        raise SystemExit(
            f"refusing non-empty output directory (stale-evidence guard): {path}"
        )
    path.mkdir(parents=True, exist_ok=True)


def quote_hit_path(path: Path) -> str:
    # HIT strings are single-quoted here; reject the only character that would
    # make the generated overlay ambiguous rather than trying to invent escaping.
    text = str(path)
    if "'" in text:
        raise SystemExit(f"output path contains unsupported single quote: {path}")
    return f"'{text}'"


def write_overlay(path: Path, metrics_base: Path) -> None:
    text = f"""# Generated by scripts/r32_profile_qpx_case.py for issue #32.
# Diagnostics only: no physics, dt, tolerance, or solver-type changes.

[Postprocessors]
  [r32_num_dofs]
    type = NumDOFs
    system = NL
    execute_on = 'initial timestep_end'
  []
  [r32_nonlinear_iterations]
    type = NumNonlinearIterations
    execute_on = timestep_end
  []
  [r32_linear_iterations]
    type = NumLinearIterations
    execute_on = timestep_end
  []
  [r32_residual_evaluations]
    type = NumResidualEvaluations
    execute_on = timestep_end
  []
[]

[Outputs]
  [r32_perfgraph]
    type = PerfGraphOutput
    execute_on = final
    level = 3
    heaviest_branch = true
    heaviest_sections = 40
  []
  [r32_metrics]
    type = CSV
    file_base = {quote_hit_path(metrics_base)}
    show = 'r32_num_dofs r32_nonlinear_iterations r32_linear_iterations r32_residual_evaluations'
    execute_on = 'initial timestep_end'
  []
[]
"""
    path.write_text(text)


def stream_process(cmd: list[str], cwd: Path, log_path: Path) -> tuple[int, float]:
    start = time.perf_counter()
    with log_path.open("w", buffering=1) as log:
        print("COMMAND    :", " ".join(cmd))
        print("CASE START :", datetime.now(timezone.utc).isoformat())
        log.write("COMMAND: " + " ".join(cmd) + "\n")
        log.write("CASE START: " + datetime.now(timezone.utc).isoformat() + "\n")
        log.flush()

        proc = subprocess.Popen(
            cmd,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert proc.stdout is not None
        try:
            for line in proc.stdout:
                sys.stdout.write(line)
                sys.stdout.flush()
                log.write(line)
                log.flush()
            rc = proc.wait()
        except KeyboardInterrupt:
            proc.terminate()
            try:
                rc = proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
                rc = proc.wait()
            raise

        elapsed = time.perf_counter() - start
        end_stamp = datetime.now(timezone.utc).isoformat()
        print(f"CASE END   : {end_stamp} rc={rc} wall_s={elapsed:.6f}")
        log.write(f"CASE END: {end_stamp} rc={rc} wall_s={elapsed:.6f}\n")
        log.flush()
    return rc, elapsed


def run_capture(cmd: list[str], cwd: Path, log_path: Path) -> int:
    with log_path.open("w") as log:
        proc = subprocess.run(
            cmd,
            cwd=cwd,
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
        )
    return proc.returncode


def find_metrics_csv(metrics_base: Path) -> Path | None:
    direct = Path(str(metrics_base) + ".csv")
    if direct.is_file():
        return direct
    matches = sorted(metrics_base.parent.glob(metrics_base.name + "*.csv"))
    return matches[0] if matches else None


def read_last_metrics_row(csv_path: Path | None) -> dict[str, str] | None:
    if csv_path is None or not csv_path.is_file():
        return None
    try:
        with csv_path.open(newline="") as f:
            rows = list(csv.DictReader(f))
    except Exception:
        return None
    return rows[-1] if rows else None


def petsc_event_hint(csv_path: Path) -> list[dict[str, str]]:
    """Best-effort extraction only; raw PETSc CSV remains canonical evidence."""
    if not csv_path.is_file():
        return []
    wanted = re.compile(
        r"KSPSolve|SNES|PCSetUp|MatLUFactor|MatCholeskyFactor|MatAssembly|MatSolve|Factor",
        re.IGNORECASE,
    )
    hits: list[dict[str, str]] = []
    try:
        with csv_path.open(newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                joined = " ".join(str(v) for v in row.values())
                if wanted.search(joined):
                    hits.append({k: v for k, v in row.items() if v not in (None, "")})
    except Exception:
        return []
    return hits[:80]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case-dir", required=True, help="Directory containing the QPX case")
    parser.add_argument("--input", required=True, help="Input filename relative to --case-dir")
    parser.add_argument("--label", required=True, help="Short case label, e.g. T2-heavy")
    parser.add_argument("--qpx", help="Explicit qpx-opt path")
    parser.add_argument(
        "--out-dir",
        help="Fresh evidence directory. Default: <case-dir>/r32_profiles/<label>_<UTC timestamp>",
    )
    args = parser.parse_args()

    case_dir = Path(args.case_dir).expanduser().resolve()
    if not case_dir.is_dir():
        raise SystemExit(f"case directory does not exist: {case_dir}")

    input_path = (case_dir / args.input).resolve()
    if input_path.parent != case_dir and case_dir not in input_path.parents:
        raise SystemExit("input must resolve inside --case-dir")
    if not input_path.is_file():
        raise SystemExit(f"input does not exist: {input_path}")

    exe = resolve_executable(case_dir, args.qpx)

    if args.out_dir:
        out_dir = Path(args.out_dir).expanduser().resolve()
    else:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        safe_label = re.sub(r"[^A-Za-z0-9_.-]+", "_", args.label).strip("_") or "case"
        out_dir = case_dir / "r32_profiles" / f"{safe_label}_{stamp}"
    ensure_fresh_output_dir(out_dir)

    overlay = out_dir / "r32_profile_overlay.i"
    metrics_base = out_dir / "r32_metrics"
    petsc_csv = out_dir / "petsc_log.csv"
    p2_log = out_dir / "p2_check_input.log"
    p3_log = out_dir / "p3_run.log"
    write_overlay(overlay, metrics_base)

    common = [
        str(exe),
        "-i",
        args.input,
        str(overlay),
        "Executioner/num_steps=1",
    ]

    # P2 construction check. No performance/physics interpretation is allowed
    # if this fails.
    p2_cmd = [*common, "--check-input"]
    print("P2 START   : qpx-opt --check-input with diagnostic overlay")
    p2_rc = run_capture(p2_cmd, case_dir, p2_log)
    print("P2 RESULT  :", "PASS" if p2_rc == 0 else f"FAIL rc={p2_rc}")
    if p2_rc != 0:
        summary = {
            "issue": 32,
            "label": args.label,
            "classification": "HARNESS_OR_CONSTRUCTION_FAIL",
            "qpx_realpath": str(exe),
            "case_dir": str(case_dir),
            "input": args.input,
            "input_sha256": sha256_file(input_path),
            "overlay_sha256": sha256_file(overlay),
            "p2_returncode": p2_rc,
            "p2_log": str(p2_log),
        }
        (out_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
        return p2_rc or 2

    # P3: preserve solver and physical input; add profiling/observability only.
    # PETSc -log_view is intentionally a command-line option.
    p3_cmd = [
        *common,
        "-log_view",
        f":{petsc_csv}:ascii_csv",
        "-log_view_memory",
        "-snes_converged_reason",
        "-ksp_converged_reason",
    ]
    p3_rc, wall_s = stream_process(p3_cmd, case_dir, p3_log)

    metrics_csv = find_metrics_csv(metrics_base)
    last_metrics = read_last_metrics_row(metrics_csv)
    petsc_hints = petsc_event_hint(petsc_csv)

    summary = {
        "issue": 32,
        "label": args.label,
        "classification": "PROFILE_CAPTURED" if p3_rc == 0 else "RUNTIME_FAIL_OR_NONCONVERGENCE",
        "qpx_realpath": str(exe),
        "case_dir": str(case_dir),
        "input": args.input,
        "input_sha256": sha256_file(input_path),
        "overlay_sha256": sha256_file(overlay),
        "one_step_override": "Executioner/num_steps=1",
        "physics_parameters_changed": False,
        "solver_tolerances_changed": False,
        "p2_returncode": p2_rc,
        "p3_returncode": p3_rc,
        "wall_seconds": wall_s,
        "metrics_csv": str(metrics_csv) if metrics_csv else None,
        "last_metrics_row": last_metrics,
        "perfgraph_log": str(p3_log),
        "petsc_log_csv": str(petsc_csv),
        "petsc_event_hints": petsc_hints,
    }
    summary_path = out_dir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2) + "\n")

    print("R32 SUMMARY:")
    print(f"  OUTPUT_DIR : {out_dir}")
    print(f"  WALL_S     : {wall_s:.6f}")
    print(f"  P3_RC      : {p3_rc}")
    if last_metrics:
        print("  METRICS    :", json.dumps(last_metrics, sort_keys=True))
    else:
        print("  METRICS    : unavailable; inspect run/PETSc logs")
    print(f"  SUMMARY    : {summary_path}")
    print(f"  PERFGRAPH  : {p3_log}")
    print(f"  PETSC_CSV  : {petsc_csv}")

    return p3_rc


if __name__ == "__main__":
    raise SystemExit(main())
