"""Compatibility facade for execution workspace inventory utilities."""

from .execution.workspace import (
    ComparisonRecord,
    ManifestStatus,
    WorkspaceComparison,
    WorkspaceFile,
    WorkspaceInventory,
    compare_workspaces,
    comparison_to_dict,
    discover_manifests,
    find_text_references,
    hash_file,
    inventory_cli,
    inventory_to_dict,
    inventory_workspace,
    is_generated_candidate,
    load_manifest,
    manifest_type,
    self_test,
    summarize_workspace,
    validate_manifest,
)

__all__ = [
    "ComparisonRecord",
    "ManifestStatus",
    "WorkspaceComparison",
    "WorkspaceFile",
    "WorkspaceInventory",
    "compare_workspaces",
    "comparison_to_dict",
    "discover_manifests",
    "find_text_references",
    "hash_file",
    "inventory_cli",
    "inventory_to_dict",
    "inventory_workspace",
    "is_generated_candidate",
    "load_manifest",
    "manifest_type",
    "self_test",
    "summarize_workspace",
    "validate_manifest",
]
